name: Run Cypress Tests - 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run run:e2e
          browser: chrome

      # - name: Export reports
      #   if: always()
      #   run: |
      #     npx mochawesome-merge "cypress/results/*.json" > mochawesome.json
      #     npx marge mochawesome.json

