name: Run Cypress Tests - manual

# on: push
on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          BASE_URL: https://dev2.tospo-keiba.jp
        with:
          browser: chrome
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "data.json"
          folderId: "1exjAbhv-WgDX61yjSWYn-WXNb4nc-dFz"
          name: "documentation.zip" # optional string
          overwrite: "false" # optional boolean
      # - name: Configure AWS credentials
      #   if: always()
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #       aws-access-key-id: ${{ secrets.DEV2_AWS_ACCESS_KEY_ID }}
      #       aws-secret-access-key: ${{ secrets.DEV2_AWS_SECRET_ACCESS_KEY }}
      #       aws-region: ${{ secrets.DEV2_AWS_REGION }}
  
      # - name: Upload File
      #   if: always()
      #   run: |
      #       aws s3 cp data s3://dev2-tospo-evidences/temp-cypress --recursive
    
